In [76]:
import pandas as pd
import numpy as np
import re
import csv

df = pd.read_excel('商品和服务税收分类编码表.xls',header=None)

df = df.drop(columns=[0,1,2,3,4,5,6,7,8,9,10],index=[0]) 
df = df.drop(index=[1]) 

df.columns = ["code","secondCategory","firstCategory","info"]
df

,code,secondCategory,firstCategory,info
2,1000000000000000000,货物,货物,NaN
3,1010000000000000000,农、林、牧、渔业类产品,农产品,NaN
4,1010100000000000000,农业产品,农业产品,NaN
5,1010101000000000000,谷物,谷物,包括稻谷、小麦、玉米、谷子、高粱、大麦、燕麦、黑麦、荞麦、其他谷物，不包括种用谷物（详见10...
6,1010101010000000000,稻谷,谷物,包括早籼稻、晚籼稻、中籼稻、粳稻、糯稻、其他稻谷。
...,...,...,...,...
4202,6080000000000000000,资产重组涉及的土地使用权,资产重组涉及的土地使用权,NaN
4203,6090000000000000000,代理进口免税货物货款,代理进口免税货物货款,NaN
4204,6100000000000000000,有奖发票奖金支付,有奖发票奖金,NaN
4205,6110000000000000000,不征税自来水,不征税自来水,NaN
4206,6120000000000000000,建筑服务预收款,建筑服务预收款,NaN

In [50]:
from decimal import Decimal
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None) 

data = df[(df[13] == '水果') | (df[13]=="罐头")|(df[13]=="坚果")|(df[13]=="蔬菜")|(df[13]=="谷物加工品")|(df[13]=="植物油")|
         (df[13]=="淀粉制品")|(df[13]=="谷物")|(df[13]=="果类加工品")|(df[13]==" 蛋制品")|(df[13]=="酒")|
         (df[13]=="水产加工品")|(df[13]=="软饮料")|(df[13]=="冷冻饮品")|(df[13]=="熟肉制品")|(df[13]=="原盐")|(df[13]=="油料")|
         (df[13]=="糖果类食品")|(df[13]=="焙烤食品")|(df[13]=="糖料")|(df[13]=="糖")|(df[13]=="干豆")|
         (df[13]=="食品用原料")|(df[13]=="发酵类制品")|(df[13]=="薯类")|(df[13]=="茶")|(df[13]=="豆制品")|(df[13]=="乳制品")|
         (df[13]=="肉及肉制品")|(df[13]=="谷物细粉")|(df[13]=="方便食品")|(df[13]=="薯类")|(df[13]=="薯类")|(df[13]=="水果及坚果")|
         (df[13]=="茶及饮料")|(df[13]=="食品用原料")|(df[13]=="营养保健食品")|(df[13]=="乳制品")|(df[13]=="薯豆加工品")|
         (df[13]=="食品添加剂")|(df[13]=="食品类产品")|(df[13]=="加工盐")|(df[13]=="植物加工品")|(df[13]=="蔬菜加工品")]

data = data.reset_index(drop=True)
for index, i in enumerate(data[12]):
    if(pd.isnull(data[12][index])!=True):
        if("其他"  in data[12][index]):
            data[12][index] = ""
        if(data[12][index] in  ["边销茶","水果（园林水果）","柑橘类水果"]):
            data[12][index] = ""
        if(bool(re.search(r'\d', data[12][index] ))): # 去掉含有数字的
            data[12][index] = ""
        
        data[12][index]  = re.sub('\（.*\）','',data[12][index] )
        
data = data[ data[12]!= ""]
data = data.reset_index(drop=True)
data.columns=["code","secondCategory","FirstCategory","info"]

data

,code,secondCategory,FirstCategory,info
0,1010101000000000000,谷物,谷物,包括稻谷、小麦、玉米、谷子、高粱、大麦、燕麦、黑麦、荞麦、其他谷物，不包括种用谷物（详见10...
1,1010101010000000000,稻谷,谷物,包括早籼稻、晚籼稻、中籼稻、粳稻、糯稻、其他稻谷。
2,1010101020000000000,小麦,谷物,包括硬质小麦、软质小麦、其他小麦。
3,1010101030000000000,玉米,谷物,包括白玉米、黄玉米、糯玉米、甜玉米、其他玉米。
4,1010101040000000000,谷子,谷物,包括硬谷子、糯谷子、其他谷子。
...,...,...,...,...
256,1030307060000000000,咖啡饮料,软饮料,指以咖啡的水提取液或其浓缩液、速溶咖啡粉为原料，经加工制成的液体饮料；包括咖啡因含量≥400...
257,1030307070000000000,固体饮料,软饮料,指用食品原料、食品添加剂等加工制成粉末状、颗粒状或块状等固态料的供冲调饮用的制品[固体饮料在...
258,1030308000000000000,精制茶及茶制品,茶,NaN
259,1030308010000000000,精制茶,茶,指对毛茶或半成品原料茶进行筛分、轧切、风选、干燥、匀堆、拼配等工序加工成的精茶
260,1030308020000000000,茶制品,茶,NaN

In [5]:
import pandas as pd
import requests
import json
import time
import random

# 根据页面爬取。淘宝一个页面有44的产品
def format_url(base, pages):    
    urls = []
    for i in range(0, pages*44, 44):
        urls.append(base[:-1] + str(i))
    return urls

# 解析静态html
def parse_page(url,cookies,headers,productCategory):
    result = pd.DataFrame()
    html = requests.get(url,headers = headers,cookies = cookies)
    bs = html.text
    start = bs.find('g_page_config = ') + len('g_page_config = ')
    end = bs.find('"shopcardOff":true}') + len('"shopcardOff":true}')
    js = json.loads(bs[start:end + 1])

    # 嵌套数据所在处
    for i in js['mods']['itemlist']['data']['auctions']:
        product = i['raw_title']  # 产品名
        r = pd.DataFrame({'secondCategory':productCategory,'item':[product]})
        result = pd.concat([result,r])
        
    # 每隔15～30秒发送一次请求
    time.sleep(random.uniform(15.1,30.1))
    return result

In [ ]:
result = pd.DataFrame()
for i in data["secondCategory"]:
    productCategory = i
    base_url = 'https://s.taobao.com/search?q='+productCategory+'&imgfile=&js=1&stats_click=search_radio_tmall%3A1&initiative_id=staobaoz_20200730&tab=mall&ie=utf8'

    # 输入自己登入后获取的cookies，user-agent
    cookies = {'cookie':'t=cf53c26487b40ac179b0a5121569b836; _samesite_flag_=true; cookie2=1b1c05a4a23cc7821a972cdaaba591cc; _tb_token_=eb8360881713e; _fbp=fb.1.1596032454864.2094185687; enc=FfQoyKUwp%2B%2BchJvEU8JfhzMIte%2F%2Bnpr0h7hwn%2FEOSvALxQOjGlW%2FssUS9bQSO2mO5wkzQtdVcwGZpfW3BNy6Yw%3D%3D; hng=CN%7Czh-CN%7CCNY%7C156; thw=cn; alitrackid=login.taobao.com; lastalitrackid=login.taobao.com; _m_h5_tk=53a6ca7b7757dabc66e9b059bd1f72c8_1596113984295; _m_h5_tk_enc=0f64e865c3df0d9ebb02bb4f9bc2c473; mt=ci=0_0; JSESSIONID=6C4E3C0088EC0A5266ECA0A45578B4ED; cna=CdRlFcdvLmsCAbesgLN0gUUM; l=eBPG9Kmeq5C4SKpyBOfZhurza779OIRfIuPzaNbMiOCPOyfH5jZPWZom7_TMCnhNnsGH-3rsvp1gBy8ZVyz6h6Yl3ZQ7XPQond6G.; isg=BIWF8k25difqrlC7iPDGtKQLlMe_QjnUl7OnQIfqYLzLHqSQTZHIpdD8KUrof1GM; tfstk=cqlOBSVp9eQTpVUKzAp3c7eGNuYlZDvL0OZlMEjQc9B5XufAimcowrRJ5zsT9eC..; sgcookie=EhkjFDIJO2ZCppKPpYZ8B; unb=3398939849; uc1=pas=0&cookie15=UIHiLt3xD8xYTw%3D%3D&cookie14=UoTV6hrNG4rmAA%3D%3D&existShop=false&cookie16=WqG3DMC9UpAPBHGz5QBErFxlCA%3D%3D&cookie21=U%2BGCWk%2F7p4mBoUyS4E9C; uc3=vt3=F8dBxGym7jujXhZeoBE%3D&id2=UNN0kUtSFvhkTA%3D%3D&nk2=ttQo6nL3JzalfVX%2B&lg2=URm48syIIVrSKA%3D%3D; csg=06f53ac5; lgc=%5Cu5F20%5Cu7444%5Cu5EAD990222; cookie17=UNN0kUtSFvhkTA%3D%3D; dnk=%5Cu5F20%5Cu7444%5Cu5EAD990222; skt=12bd6264f43c5f8c; existShop=MTU5NjEzNTY4OQ%3D%3D; uc4=id4=0%40UgQ8euecqzo33MuZDp3BDEsfitEN&nk4=0%40tAKcNkLpTgCP0drR5fRTgK2iWrubUuc%3D; tracknick=%5Cu5F20%5Cu7444%5Cu5EAD990222; _cc_=UtASsssmfA%3D%3D; _l_g_=Ug%3D%3D; sg=29a; _nk_=%5Cu5F20%5Cu7444%5Cu5EAD990222; cookie1=B0AEj857kxH%2F4KnrJMouZmBJFb6kxPCTyy3hwIKzpV4%3D'}
    headers = {'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'}


    final_result = pd.DataFrame()
    for url in format_url(base_url,1): # 第二个参数是希望爬取的页数
        final_result = pd.concat([final_result,parse_page(url,cookies = cookies,headers = headers,productCategory=productCategory)])

#     print(final_result)
    result = pd.concat([result,final_result])

In [66]:
#result#.to_csv("dataAugmentation.csv")

result = pd.read_csv("webCrawlData.csv",index_col=0)

# df = pd.read_excel('税收分类编码匹配示例库.xlsx')
# df.columns = ["item","code","secondCategory","firstCategory"]
df.columns = ["code","secondCategory","firstCategory","item"]
df = df[["code","secondCategory","firstCategory"]]
df

ValueError: Length mismatch: Expected axis has 3 elements, new values have 4 elements

In [83]:
import jieba as jb
#定义删除除字母,数字，汉字以外的所有符号的函数
def remove_punctuation(line):
    line = str(line)
    if line.strip()=='':
        return ''
    rule = re.compile(u"[^\u4E00-\u9FA5]")
    line = rule.sub('',line)
    return line
 
def stopwordslist(filepath):  
    stopwords = [line.strip() for line in open(filepath, 'r', encoding='utf-8').readlines()]  
    return stopwords  
 
#加载停用词
stopwords = stopwordslist("chineseStopWords.txt")

#删除除字母,数字，汉字以外的所有符号
result['item'] = result['item'].apply(remove_punctuation)


#分词，并过滤停用词
result['item']= result['item'].apply(lambda x: "".join([w for w in list(jb.cut(x)) if w not in stopwords]))



result= result[["item","secondCategory"]]

      
result

                          item secondCategory
0           家乐氏原味玉米片即食冲饮谷物早餐干吃             谷物
0       年卡圣迪乐村新鲜鸡蛋枚盒谷物蛋生食无菌蛋年卡             谷物
0   风鱼饵黑坑鲤酒香谷物香虾螺腥克钓饵黑坑鲤鱼食野钓鱼料             谷物
0         椰树牌豆奶瓶整箱谷物早餐植物蛋白饮料即食             谷物
0                 发货营养麦球谷物早餐麦片             谷物
..                         ...            ...
0     舌里红枣片若羌无核红枣干泡茶香酥脆枣零食小灰枣子            茶制品
0         黑枸杞非野生小袋装正品礼盒搭枸杞红枣黄芪            茶制品
0     野生正品黑枸杞子黑构杞纪苟杞子特級免洗黑果泡茶水            茶制品
0        好想你红枣干袋枣片泡水干吃泡茶无核免洗零食            茶制品
0           思宏厚切枣圈一级灰枣片干吃泡茶脆枣子            茶制品

[10166 rows x 2 columns]

In [84]:
res = pd.merge(result, df, how='left', on=['secondCategory'])
res = res[["item","code","secondCategory","firstCategory"]]
res

,item,code,secondCategory,firstCategory
0,家乐氏原味玉米片即食冲饮谷物早餐干吃,1010101000000000000,谷物,谷物
1,年卡圣迪乐村新鲜鸡蛋枚盒谷物蛋生食无菌蛋年卡,1010101000000000000,谷物,谷物
2,风鱼饵黑坑鲤酒香谷物香虾螺腥克钓饵黑坑鲤鱼食野钓鱼料,1010101000000000000,谷物,谷物
3,椰树牌豆奶瓶整箱谷物早餐植物蛋白饮料即食,1010101000000000000,谷物,谷物
4,发货营养麦球谷物早餐麦片,1010101000000000000,谷物,谷物
...,...,...,...,...
10161,舌里红枣片若羌无核红枣干泡茶香酥脆枣零食小灰枣子,1030308020000000000,茶制品,茶
10162,黑枸杞非野生小袋装正品礼盒搭枸杞红枣黄芪,1030308020000000000,茶制品,茶
10163,野生正品黑枸杞子黑构杞纪苟杞子特級免洗黑果泡茶水,1030308020000000000,茶制品,茶
10164,好想你红枣干袋枣片泡水干吃泡茶无核免洗零食,1030308020000000000,茶制品,茶
10165,思宏厚切枣圈一级灰枣片干吃泡茶脆枣子,1030308020000000000,茶制品,茶

In [85]:
df2 = pd.read_excel('税收分类编码匹配示例库.xlsx')
df2.columns = ["item","code","secondCategory","firstCategory"]
df2

             item                 code secondCategory firstCategory
0             蛋奶液  1030204010000000000            液体乳           乳制品
1           打发淡奶油  1030204010000000000            液体乳           乳制品
2         茉莉花茶蛋奶液  1030204010000000000            液体乳           乳制品
3         焦糖布丁蛋奶液  1030204010000000000            液体乳           乳制品
4           法式甜奶油  1030204020000000000      固体及半固体乳制品           乳制品
..            ...                  ...            ...           ...
545     丙烯羊毛混V字领衫  1040201110000000000            女上衣            服装
546      丙烯羊毛混圆领衫  1040201110000000000            女上衣            服装
547  丝光斜纹弹力五分长工装裤  1040201240000000000          婴幼儿服装            服装
548      丝光斜纹弹力裤子  1040201240000000000          婴幼儿服装            服装
549    丝光斜纹弹力陀螺形裤  1040201240000000000          婴幼儿服装            服装

[550 rows x 4 columns]

In [86]:
frames = [df2, res]
 
f = pd.concat(frames)
f = f[["code","secondCategory","firstCategory","item"]]
f

,code,secondCategory,firstCategory,item
0,1030204010000000000,液体乳,乳制品,蛋奶液
1,1030204010000000000,液体乳,乳制品,打发淡奶油
2,1030204010000000000,液体乳,乳制品,茉莉花茶蛋奶液
3,1030204010000000000,液体乳,乳制品,焦糖布丁蛋奶液
4,1030204020000000000,固体及半固体乳制品,乳制品,法式甜奶油
...,...,...,...,...
10161,1030308020000000000,茶制品,茶,舌里红枣片若羌无核红枣干泡茶香酥脆枣零食小灰枣子
10162,1030308020000000000,茶制品,茶,黑枸杞非野生小袋装正品礼盒搭枸杞红枣黄芪
10163,1030308020000000000,茶制品,茶,野生正品黑枸杞子黑构杞纪苟杞子特級免洗黑果泡茶水
10164,1030308020000000000,茶制品,茶,好想你红枣干袋枣片泡水干吃泡茶无核免洗零食
10165,1030308020000000000,茶制品,茶,思宏厚切枣圈一级灰枣片干吃泡茶脆枣子

In [77]:
df

,code,secondCategory,firstCategory,info
2,1000000000000000000,货物,货物,NaN
3,1010000000000000000,农、林、牧、渔业类产品,农产品,NaN
4,1010100000000000000,农业产品,农业产品,NaN
5,1010101000000000000,谷物,谷物,包括稻谷、小麦、玉米、谷子、高粱、大麦、燕麦、黑麦、荞麦、其他谷物，不包括种用谷物（详见10...
6,1010101010000000000,稻谷,谷物,包括早籼稻、晚籼稻、中籼稻、粳稻、糯稻、其他稻谷。
...,...,...,...,...
4202,6080000000000000000,资产重组涉及的土地使用权,资产重组涉及的土地使用权,NaN
4203,6090000000000000000,代理进口免税货物货款,代理进口免税货物货款,NaN
4204,6100000000000000000,有奖发票奖金支付,有奖发票奖金,NaN
4205,6110000000000000000,不征税自来水,不征税自来水,NaN
4206,6120000000000000000,建筑服务预收款,建筑服务预收款,NaN

In [93]:
df['FirstCategoryID'] = df['firstCategory'].factorize()[0]
df['SecondCategoryID'] = df['secondCategory'].factorize()[0]
cat_id_df = df[['firstCategory', 'FirstCategoryID']].drop_duplicates().sort_values('FirstCategoryID').reset_index(drop=True)
cat_id_df2 = df[['secondCategory', 'SecondCategoryID']].drop_duplicates().sort_values('SecondCategoryID').reset_index(drop=True)
cat_to_id = dict(cat_id_df.values)
cat_to_id2 = dict(cat_id_df2.values)
id_to_cat = dict(cat_id_df[['FirstCategoryID', 'firstCategory']].values)
id_to_cat2 = dict(cat_id_df2[['SecondCategoryID', 'secondCategory']].values)
df
df = df[["code","firstCategory","FirstCategoryID","secondCategory","SecondCategoryID","info"]]

df#.to_csv("taxData.csv")

,code,firstCategory,FirstCategoryID,secondCategory,SecondCategoryID,info
2,1000000000000000000,货物,0,货物,0,NaN
3,1010000000000000000,农产品,1,农、林、牧、渔业类产品,1,NaN
4,1010100000000000000,农业产品,2,农业产品,2,NaN
5,1010101000000000000,谷物,3,谷物,3,包括稻谷、小麦、玉米、谷子、高粱、大麦、燕麦、黑麦、荞麦、其他谷物，不包括种用谷物（详见10...
6,1010101010000000000,谷物,3,稻谷,4,包括早籼稻、晚籼稻、中籼稻、粳稻、糯稻、其他稻谷。
...,...,...,...,...,...,...
4202,6080000000000000000,资产重组涉及的土地使用权,404,资产重组涉及的土地使用权,4194,NaN
4203,6090000000000000000,代理进口免税货物货款,405,代理进口免税货物货款,4195,NaN
4204,6100000000000000000,有奖发票奖金,406,有奖发票奖金支付,4196,NaN
4205,6110000000000000000,不征税自来水,407,不征税自来水,4197,NaN
4206,6120000000000000000,建筑服务预收款,408,建筑服务预收款,4198,NaN

In [91]:
t=f[["secondCategory","item"]]
res = pd.merge(t, df, how='left', on=['secondCategory'])
res = res[["item","code","firstCategory","FirstCategoryID","secondCategory","SecondCategoryID"]]
res#.to_csv("itemData.csv")

,item,code,firstCategory,FirstCategoryID,secondCategory,SecondCategoryID
0,蛋奶液,1030204010000000000,乳制品,74.0,液体乳,509.0
1,打发淡奶油,1030204010000000000,乳制品,74.0,液体乳,509.0
2,茉莉花茶蛋奶液,1030204010000000000,乳制品,74.0,液体乳,509.0
3,焦糖布丁蛋奶液,1030204010000000000,乳制品,74.0,液体乳,509.0
4,法式甜奶油,1030204020000000000,乳制品,74.0,固体及半固体乳制品,510.0
...,...,...,...,...,...,...
10711,舌里红枣片若羌无核红枣干泡茶香酥脆枣零食小灰枣子,1030308020000000000,茶,88.0,茶制品,585.0
10712,黑枸杞非野生小袋装正品礼盒搭枸杞红枣黄芪,1030308020000000000,茶,88.0,茶制品,585.0
10713,野生正品黑枸杞子黑构杞纪苟杞子特級免洗黑果泡茶水,1030308020000000000,茶,88.0,茶制品,585.0
10714,好想你红枣干袋枣片泡水干吃泡茶无核免洗零食,1030308020000000000,茶,88.0,茶制品,585.0
10715,思宏厚切枣圈一级灰枣片干吃泡茶脆枣子,1030308020000000000,茶,88.0,茶制品,585.0